[package]
name = "injectium-core"
description = "Core implementation and utilities for injectium"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["sync"]
debug = []
sync = []
ahash = ["dep:ahash"]

[dependencies]
ahash = { version = "0.8", optional = true }
cfg_block.workspace = true
inventory.workspace = true
