[package]
name = "injectium-core"
description = "Core implementation and utilities for injectium"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["sync", "validation"]
debug = []
sync = []
validation = ["dep:inventory"]

[dependencies]
cfg_block.workspace = true
inventory = { workspace = true, optional = true }

[dev-dependencies]
criterion = "0.8"
macrotest = "1"

[[bench]]
name = "resolve"
harness = false
