[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Ray <i@mk1.io>"]
license = "MIT"
repository = "https://github.com/so1ve/injectium"

[workspace.dependencies]
cfg_block = "0.2"
injectium = { path = "crates/injectium", version = "0.1" }
injectium-core = { path = "crates/injectium-core", version = "0.1" }
injectium-macro = { path = "crates/injectium-macro", version = "0.1" }
injectium-salvo = { path = "crates/injectium-salvo", version = "0.1" }
inventory = "0.3.22"
proc-macro2 = "1"
quote = "1"
salvo = { version = "0.89", features = ["affix-state"] }
syn = "2"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"
perf = "warn"
